# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"XMLDetectionDataset": "00_dataset.ipynb",
         "CLASSES": "00_dataset.ipynb",
         "XMLDetectionDataModule": "00_dataset.ipynb",
         "bbox_iou": "03_metrics.ipynb",
         "SingleBoxDetector": "01_cnn_module.ipynb",
         "COCO_INSTANCE_CATEGORY_NAMES": "01_cnn_module.ipynb",
         "name2idx": "01_cnn_module.ipynb",
         "sports_ball_ID": "01_cnn_module.ipynb",
         "TorchVisionDetector": "01_cnn_module.ipynb",
         "conv2d": "02_separability_filter.ipynb",
         "cvtIntegralImage": "02_separability_filter.ipynb",
         "cvtCombSimpRectFilter": "02_separability_filter.ipynb",
         "tmpFnc": "02_separability_filter.ipynb",
         "hungarian_loss": "03_metrics.ipynb",
         "random_bbox": "04_utils.ipynb",
         "visualize_bbox": "04_utils.ipynb",
         "visualize": "04_utils.ipynb",
         "plot_images": "04_utils.ipynb"}

modules = ["dataset.py",
           "cnn_module.py",
           "separability_filter.py",
           "metrics.py",
           "utils.py"]

doc_url = "https://AtomScott.github.io/ball_detection/"

git_url = "https://github.com/AtomScott/ball_detection/tree/master/"

def custom_doc_links(name): return None
