# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_images": "01_utils.ipynb"}

modules = ["RSF.py",
           "utils.py"]

doc_url = "https://AtomScott.github.io/RSF/"

git_url = "https://github.com/AtomScott/RSF/tree/master/"

def custom_doc_links(name): return None
