# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_utils.ipynb (unless otherwise specified).

__all__ = ['plot_images']

# Cell
import glob
import os

import matplotlib.pyplot as plt
import numpy as np
import torch as t
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from fastai.vision.data import get_grid
from PIL import Image
from PIL.JpegImagePlugin import JpegImageFile
from torchvision import transforms

from einops import rearrange

# Cell
def plot_images(images):
    n = len(images)
    axs = get_grid(n, figsize=(12,9))
    for ax, im in zip(axs, images):
        if im.shape[0]==1:
            im = rearrange(im, 'c h w -> h w c')
            ax.imshow(im, cmap='gray')
        elif im.shape[0]==3:
            im = rearrange(im, 'c h w -> h w c')
            ax.imshow(im)
        else:
            ax.imshow(im)
        ax.axis('off')
    plt.show()
